#!/usr/bin/env python3
"""
ga4-tracking-wiring.py — Scaffold GA4 event tracking into a Next.js App Router project.

Generates a typed gtag wrapper, four event helpers, and four client components:
  - lib/analytics/ga4.ts
  - lib/analytics/events.ts
  - components/analytics/CTAButton.tsx
  - components/analytics/OutboundLink.tsx
  - components/analytics/ScrollDepthTracker.tsx
  - components/analytics/ReadCompleteTracker.tsx

And optionally patches app/layout.tsx to mount <ScrollDepthTracker />.

Usage:
  python3 ga4-tracking-wiring.py --target ./my-nextjs-app --dry-run
  python3 ga4-tracking-wiring.py --target ./my-nextjs-app --apply
  python3 ga4-tracking-wiring.py --target ./my-nextjs-app --events cta,outbound --apply
  python3 ga4-tracking-wiring.py --measurement-id G-XXXXXXXXXX --apply
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

ALL_EVENTS = ("cta", "outbound", "scroll", "read")
MEASUREMENT_ID_RE = re.compile(r"^G-[A-Z0-9]{10}$")


@dataclass
class Plan:
    creates: list[tuple[str, str]] = field(default_factory=list)  # (relpath, content)
    conflicts: list[str] = field(default_factory=list)
    updates: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


# ---------- template fragments ----------

def tpl_ga4_ts(measurement_id: str | None, consent_strict: bool) -> str:
    fallback = measurement_id or ""
    consent_guard = ""
    if consent_strict:
        consent_guard = """
function hasConsent(): boolean {
  if (typeof window === "undefined") return false;
  // Project-specific consent check. Replace with your CMP integration.
  return (window as unknown as { __ga4_consent?: boolean }).__ga4_consent === true;
}
"""
    consent_call = "  if (!hasConsent()) return;\n" if consent_strict else ""
    return f"""// Auto-generated by ga4-tracking-wiring skill. Edit with care.
declare global {{
  interface Window {{
    gtag?: (command: string, ...args: unknown[]) => void;
    dataLayer?: unknown[];
  }}
}}

export const GA4_MEASUREMENT_ID =
  process.env.NEXT_PUBLIC_GA4_MEASUREMENT_ID ?? {json.dumps(fallback)};
{consent_guard}
export type GA4EventParams = Record<string, string | number | boolean | undefined>;

export function gaEvent(name: string, params: GA4EventParams = {{}}): void {{
  if (typeof window === "undefined") return;
{consent_call}  if (typeof window.gtag !== "function") {{
    if (process.env.NODE_ENV !== "production") {{
      // eslint-disable-next-line no-console
      console.warn("[ga4] gtag not loaded; dropped event", name, params);
    }}
    return;
  }}
  window.gtag("event", name, params);
}}
"""


def tpl_events_ts() -> str:
    return """// Auto-generated by ga4-tracking-wiring skill.
import { gaEvent } from "./ga4";

export type CTAPosition = "hero" | "header" | "footer" | "sidebar" | "inline" | string;

export function trackCTAClick(label: string, position: CTAPosition): void {
  gaEvent("cta_click", {
    event_label: label,
    cta_position: position,
  });
}

export function trackOutboundLink(url: string, domain: string, linkText?: string): void {
  gaEvent("outbound_click", {
    link_url: url,
    link_domain: domain,
    link_text: linkText,
  });
}

export type ScrollDepthPercent = 25 | 50 | 75 | 100;

export function trackScrollDepth(percent: ScrollDepthPercent): void {
  gaEvent("scroll_depth", {
    percent_scrolled: percent,
  });
}

export function trackReadComplete(articleSlug: string, dwellSec?: number): void {
  gaEvent("read_complete", {
    article_slug: articleSlug,
    dwell_sec: dwellSec,
  });
}
"""


def tpl_cta_button_tsx() -> str:
    return """"use client";
// Auto-generated by ga4-tracking-wiring skill.
import Link from "next/link";
import type { ReactNode, MouseEvent } from "react";
import { trackCTAClick, type CTAPosition } from "@/lib/analytics/events";

export interface CTAButtonProps {
  label: string;
  position: CTAPosition;
  href: string;
  children: ReactNode;
  className?: string;
  onClick?: (e: MouseEvent<HTMLAnchorElement>) => void;
}

export function CTAButton({
  label,
  position,
  href,
  children,
  className,
  onClick,
}: CTAButtonProps) {
  const handle = (e: MouseEvent<HTMLAnchorElement>) => {
    trackCTAClick(label, position);
    onClick?.(e);
  };
  const isExternal = /^https?:\\/\\//.test(href);
  if (isExternal) {
    return (
      <a
        href={href}
        className={className}
        onClick={handle}
        target="_blank"
        rel="noopener noreferrer"
      >
        {children}
      </a>
    );
  }
  return (
    <Link href={href} className={className} onClick={handle}>
      {children}
    </Link>
  );
}
"""


def tpl_outbound_link_tsx() -> str:
    return """"use client";
// Auto-generated by ga4-tracking-wiring skill.
import type { ReactNode, MouseEvent } from "react";
import { trackOutboundLink } from "@/lib/analytics/events";

export interface OutboundLinkProps {
  href: string;
  children: ReactNode;
  className?: string;
  onClick?: (e: MouseEvent<HTMLAnchorElement>) => void;
}

export function OutboundLink({ href, children, className, onClick }: OutboundLinkProps) {
  const handle = (e: MouseEvent<HTMLAnchorElement>) => {
    try {
      const url = new URL(href);
      if (typeof window !== "undefined" && url.hostname !== window.location.hostname) {
        const text = typeof children === "string" ? children : undefined;
        trackOutboundLink(url.toString(), url.hostname, text);
      }
    } catch {
      // ignore malformed URL
    }
    onClick?.(e);
  };
  return (
    <a
      href={href}
      className={className}
      onClick={handle}
      target="_blank"
      rel="noopener noreferrer"
    >
      {children}
    </a>
  );
}
"""


def tpl_scroll_depth_tracker_tsx(thresholds: list[int]) -> str:
    thresholds_js = ", ".join(str(t) for t in thresholds)
    return f""""use client";
// Auto-generated by ga4-tracking-wiring skill.
import {{ useEffect, useRef }} from "react";
import {{ usePathname }} from "next/navigation";
import {{ trackScrollDepth, type ScrollDepthPercent }} from "@/lib/analytics/events";

const THRESHOLDS: ScrollDepthPercent[] = [{thresholds_js}] as ScrollDepthPercent[];

export function ScrollDepthTracker() {{
  const pathname = usePathname();
  const firedRef = useRef<Set<number>>(new Set());

  useEffect(() => {{
    firedRef.current = new Set();
    if (typeof window === "undefined") return;

    const handler = () => {{
      const doc = document.documentElement;
      const scrollTop = window.scrollY || doc.scrollTop;
      const viewport = window.innerHeight || doc.clientHeight;
      const full = doc.scrollHeight - viewport;
      if (full <= 0) return;
      const percent = Math.min(100, Math.round((scrollTop / full) * 100));
      for (const t of THRESHOLDS) {{
        if (percent >= t && !firedRef.current.has(t)) {{
          firedRef.current.add(t);
          trackScrollDepth(t);
        }}
      }}
    }};

    window.addEventListener("scroll", handler, {{ passive: true }});
    handler();
    return () => window.removeEventListener("scroll", handler);
  }}, [pathname]);

  return null;
}}
"""


def tpl_read_complete_tracker_tsx(read_percent: int, dwell_sec: int) -> str:
    return f""""use client";
// Auto-generated by ga4-tracking-wiring skill.
import {{ useEffect, useRef }} from "react";
import {{ trackReadComplete }} from "@/lib/analytics/events";

export interface ReadCompleteTrackerProps {{
  articleSlug: string;
  scrollPercent?: number;
  dwellSec?: number;
}}

export function ReadCompleteTracker({{
  articleSlug,
  scrollPercent = {read_percent},
  dwellSec = {dwell_sec},
}}: ReadCompleteTrackerProps) {{
  const firedRef = useRef(false);
  const mountedAtRef = useRef<number>(Date.now());
  const scrollReachedRef = useRef(false);

  useEffect(() => {{
    if (typeof window === "undefined") return;
    firedRef.current = false;
    mountedAtRef.current = Date.now();
    scrollReachedRef.current = false;

    const maybeFire = () => {{
      if (firedRef.current) return;
      const dwell = (Date.now() - mountedAtRef.current) / 1000;
      if (scrollReachedRef.current && dwell >= dwellSec) {{
        firedRef.current = true;
        trackReadComplete(articleSlug, Math.round(dwell));
      }}
    }};

    const scrollHandler = () => {{
      const doc = document.documentElement;
      const scrollTop = window.scrollY || doc.scrollTop;
      const viewport = window.innerHeight || doc.clientHeight;
      const full = doc.scrollHeight - viewport;
      if (full <= 0) return;
      const percent = Math.min(100, Math.round((scrollTop / full) * 100));
      if (percent >= scrollPercent) {{
        scrollReachedRef.current = true;
        maybeFire();
      }}
    }};

    const dwellTimer = window.setInterval(maybeFire, 1000);
    window.addEventListener("scroll", scrollHandler, {{ passive: true }});
    scrollHandler();
    return () => {{
      window.removeEventListener("scroll", scrollHandler);
      window.clearInterval(dwellTimer);
    }};
  }}, [articleSlug, scrollPercent, dwellSec]);

  return null;
}}
"""


# ---------- planner ----------

def detect_layout_path(target: Path) -> Path | None:
    for cand in ("app/layout.tsx", "src/app/layout.tsx", "app/layout.jsx"):
        p = target / cand
        if p.exists():
            return p
    return None


def validate(target: Path, measurement_id: str | None, plan: Plan) -> None:
    app_dir = target / "app"
    src_app = target / "src" / "app"
    if not app_dir.exists() and not src_app.exists():
        plan.errors.append(
            f"target {target} does not look like a Next.js App Router project (no app/ or src/app/)"
        )

    mid = measurement_id or os.environ.get("NEXT_PUBLIC_GA4_MEASUREMENT_ID")
    if not mid:
        plan.errors.append(
            "no GA4 measurement ID: pass --measurement-id or set NEXT_PUBLIC_GA4_MEASUREMENT_ID"
        )
    elif not MEASUREMENT_ID_RE.match(mid):
        plan.errors.append(
            f"measurement ID {mid!r} does not match G-[A-Z0-9]{{10}}"
        )

    pkg = target / "package.json"
    if pkg.exists():
        try:
            data = json.loads(pkg.read_text())
            next_ver = (data.get("dependencies") or {}).get("next") or (
                data.get("devDependencies") or {}
            ).get("next")
            if next_ver and not re.search(r"(\d+)", next_ver):
                pass
            elif next_ver:
                m = re.search(r"(\d+)", next_ver)
                if m and int(m.group(1)) < 14:
                    plan.warnings.append(f"next {next_ver} < 14; App Router required")
        except Exception:
            plan.warnings.append("could not parse package.json")
    else:
        plan.warnings.append("no package.json found at target root")

    layout = detect_layout_path(target)
    if layout:
        try:
            txt = layout.read_text()
            if "gtag" not in txt and "googletagmanager" not in txt.lower():
                plan.warnings.append(
                    f"{layout.relative_to(target)} does not appear to load gtag.js"
                )
        except Exception:
            pass


def file_plan(target: Path, relpath: str, content: str, plan: Plan) -> None:
    abspath = target / relpath
    if abspath.exists():
        plan.conflicts.append(relpath)
        plan.creates.append((relpath + ".new", content))
    else:
        plan.creates.append((relpath, content))


def build_plan(args: argparse.Namespace) -> Plan:
    target = Path(args.target).resolve()
    plan = Plan()
    validate(target, args.measurement_id, plan)
    if plan.errors:
        return plan

    events = set(args.events.split(",")) if args.events else set(ALL_EVENTS)
    unknown = events - set(ALL_EVENTS)
    if unknown:
        plan.errors.append(f"unknown events: {sorted(unknown)}")
        return plan

    # Core libs always generated
    file_plan(target, "lib/analytics/ga4.ts", tpl_ga4_ts(args.measurement_id, args.consent_strict), plan)
    file_plan(target, "lib/analytics/events.ts", tpl_events_ts(), plan)

    if "cta" in events:
        file_plan(target, "components/analytics/CTAButton.tsx", tpl_cta_button_tsx(), plan)
    if "outbound" in events:
        file_plan(target, "components/analytics/OutboundLink.tsx", tpl_outbound_link_tsx(), plan)
    if "scroll" in events:
        thresholds = [int(x) for x in args.scroll_thresholds.split(",")]
        file_plan(target, "components/analytics/ScrollDepthTracker.tsx",
                  tpl_scroll_depth_tracker_tsx(thresholds), plan)
    if "read" in events:
        file_plan(target, "components/analytics/ReadCompleteTracker.tsx",
                  tpl_read_complete_tracker_tsx(args.read_complete_percent, args.read_complete_dwell_sec), plan)

    if not args.no_layout_patch and "scroll" in events:
        layout = detect_layout_path(target)
        if layout:
            plan.updates.append(str(layout.relative_to(target)) + " (add ScrollDepthTracker)")
        else:
            plan.warnings.append("could not locate app/layout.tsx; skipping layout patch")
    return plan


# ---------- writer ----------

LAYOUT_PATCH_SNIPPET = """// === ga4-tracking-wiring: add this import near the top ===
import { ScrollDepthTracker } from "@/components/analytics/ScrollDepthTracker";

// === then render <ScrollDepthTracker /> inside <body>, e.g.: ===
// <body>
//   <ScrollDepthTracker />
//   {children}
// </body>
"""


def apply_plan(target: Path, plan: Plan, args: argparse.Namespace) -> None:
    for rel, content in plan.creates:
        abspath = target / rel
        abspath.parent.mkdir(parents=True, exist_ok=True)
        abspath.write_text(content)
        print(f"  WROTE {rel}")

    if not args.no_layout_patch:
        layout = detect_layout_path(target)
        if layout:
            patch_layout(layout, plan)


def patch_layout(layout: Path, plan: Plan) -> None:
    txt = layout.read_text()
    if "ScrollDepthTracker" in txt:
        print(f"  SKIP {layout.name}: ScrollDepthTracker already mounted")
        return
    # try a naive injection
    import_line = 'import { ScrollDepthTracker } from "@/components/analytics/ScrollDepthTracker";\n'
    new_txt = txt
    if "ScrollDepthTracker" not in new_txt:
        # add import after the last top-level import
        m = list(re.finditer(r"^import .+$", new_txt, flags=re.MULTILINE))
        if m:
            last = m[-1]
            new_txt = new_txt[: last.end()] + "\n" + import_line + new_txt[last.end():]
        else:
            new_txt = import_line + new_txt

    body_re = re.search(r"<body[^>]*>", new_txt)
    if not body_re:
        print("  CONFLICT layout patch: could not find <body> — see snippet below")
        print(LAYOUT_PATCH_SNIPPET)
        return
    insert_at = body_re.end()
    new_txt = new_txt[:insert_at] + "\n        <ScrollDepthTracker />" + new_txt[insert_at:]
    layout.write_text(new_txt)
    print(f"  PATCHED {layout.name}")


# ---------- main ----------

def print_plan(plan: Plan) -> None:
    print("Plan:")
    for rel, _ in plan.creates:
        kind = "CREATE" if not rel.endswith(".new") else "CREATE.new"
        print(f"  {kind} {rel}")
    for u in plan.updates:
        print(f"  UPDATE {u}")
    print(f"Existing files: {len(plan.conflicts)} conflicts")
    for c in plan.conflicts:
        print(f"  CONFLICT {c}")
        print(f"    Merge guide: diff -u {c} {c}.new")
    for w in plan.warnings:
        print(f"  WARN {w}")
    for e in plan.errors:
        print(f"  ERROR {e}")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Wire GA4 event tracking into a Next.js App Router project")
    p.add_argument("--target", default=".", help="Next.js project root")
    p.add_argument("--events", default=",".join(ALL_EVENTS),
                   help="comma-separated subset of cta,outbound,scroll,read")
    p.add_argument("--measurement-id", default=None,
                   help="GA4 measurement ID (G-XXXXXXXXXX); falls back to env NEXT_PUBLIC_GA4_MEASUREMENT_ID")
    p.add_argument("--apply", action="store_true", help="write files (default is dry-run)")
    p.add_argument("--dry-run", action="store_true", help="explicit dry-run (default)")
    p.add_argument("--no-layout-patch", action="store_true", help="skip app/layout.tsx modification")
    p.add_argument("--scroll-thresholds", default="25,50,75,100",
                   help="comma-separated scroll depth thresholds")
    p.add_argument("--read-complete-percent", type=int, default=90,
                   help="scroll percent for read_complete (default 90)")
    p.add_argument("--read-complete-dwell-sec", type=int, default=30,
                   help="min dwell seconds for read_complete (default 30)")
    p.add_argument("--consent-strict", action="store_true",
                   help="emit hasConsent() guard in ga4.ts")
    args = p.parse_args(argv)

    target = Path(args.target).resolve()
    plan = build_plan(args)
    print_plan(plan)

    if plan.errors:
        return 2
    if not args.apply:
        print("\n(dry-run) pass --apply to write files")
        return 0

    print("\nApplying...")
    apply_plan(target, plan, args)
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
